[package]
name = "rbar"
version = "0.0.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
glib = "0.18"
gtk = "0.18"
gtk-layer-shell = "0.8"
log = "0.4"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
